version: '3.9'
services:
  react_app:
    image: node:14
    working_dir: /usr/react-app
    volumes:
      - .:/usr/react-app
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: bash -c "yarn && yarn start"
